sprint 10 first
alexhved/java-filmorate pull request #3
Opened 2022-09-21 18:28 UTC by alexhved

sprint 10 first commit

2022-09-22 04:16 UTC, sergeymamonov requested changes

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.BAD_REQUEST)
400 ошибка обрабатывается два раза. Здесь и на строке 19. Разница лишь в перехватываемых ошибка. Можно сделать один перехватчик этой ошибки. Для этого нужно проверить так ли необходим второй класс ошибки?

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/ErrorHandler.java
> +public class ErrorHandler {
Может ли возникнуть 404 ошибка в приложении? Ошибка же для этого кода есть в приложении.

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmStorage filmStorage;
Контроллер не должен обращаться к стораджу. Контроллер обращается к сервису. Сервис обращается к стораджу.

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          validator.validate(film);
Валидацию нужно отправить в сервис.

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exception/IncorrectParameterException.java
> +    public IncorrectParameterException(String param) {
Проверьте, где используется эта ошибка.

2022-09-22 04:16 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/user/UserService.java
> +            throw new NotFoundException(String.format("Пользователь с id %s не найден", friendId));
Лучше писать все логи на одном языке.

2022-09-22 21:40 UTC, sergeymamonov requested changes

2022-09-22 21:40 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().getFilmById(id);
здесь нужно вызвать метод у сервиса и все. Не нужно вызывать экземпляр сервиса и вызывать у него метод.

2022-09-22 21:40 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().create(film);
Нужно вызвать только метод у сервиса. А уже в этом методе в сервисе будет вызываться валидация.

2022-09-23 16:57 UTC, alexhved commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().getFilmById(id);
ok

2022-09-23 16:57 UTC, alexhved commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.getFilmStorage().create(film);
ok

2022-09-23 16:59 UTC, alexhved commented
Исправлены замечания

2022-09-23 17:02 UTC, alexhved commented
Исправлены замечания описанные выше

2022-09-24 04:23 UTC, sergeymamonov approved these changes

2022-09-24 18:38 UTC, merged